### ISSUE TITLE
[utils][RepeatActionEnv] step function is not general

### ISSUE THREAD

**Issue by ghost** [alirezakazemipour/Rainbow#1]
If an episode terminates when t is equal to zero or one, the step function returns the maximum of the zero arrays. It's better to check the remainder of the t variable to zero and one respectively.
@alirezakazemipour

**Comment by akazemipour** [comment]
Yeah, you're right.
Actually, this module is my personal implementation of [the OpenAI's original code](https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py). Take a look at ```class MaxAndSkipEnv(gym.Wrapper)```.  
The amount of speed gotten by this class outweighs that event of obtaining zero pixels.
